### ISSUE TITLE
请问下topk_dict_path指的是什么呢？

### ISSUE THREAD

**Issue by noobexplore** [GanjinZero/CHIP2020_term_normalization#6]
topk_dict_path = "/media/sdd1/Hongyi_Yuan/CHIP2020/Final/result_dict_test/dice_train_final_v3.pkl"
这里的pkl文件如何生成呢，代码半天没找到地方，还望大佬指出。

**Comment by GanjinZero** [comment]
用rule_base/bm25.py在训练数据集上训练得到的，因为训练数据不能公布，所以没有上传这个

**Comment by andylulu** [comment]
> 用rule_base/bm25.py在训练数据集上训练得到的，因为训练数据不能公布，所以没有上传这个

大佬 能否给出代码中使用到的 一些文件 比如 train.txt等  给少许正确数据  以便好理解代码

**Comment by andylulu** [comment]
> > 用rule_base/bm25.py在训练数据集上训练得到的，因为训练数据不能公布，所以没有上传这个
> 
> 大佬 能否给出代码中使用到的 一些文件 比如 train.txt等 给少许正确数据 以便好理解代码

还有word2vec_5_300.model等

**Comment by noobexplore** [comment]
> > > 用rule_base/bm25.py在训练数据集上训练得到的，因为训练数据不能公布，所以没有上传这个
> > 
> > 
> > 大佬 能否给出代码中使用到的 一些文件 比如 train.txt等 给少许正确数据 以便好理解代码
> 
> 还有word2vec_5_300.model等

数据集已经可以在阿里天池上可以申请获取：https://tianchi.aliyun.com/dataset/dataDetail?dataId=95414# 
word2vec_5_300.model 这个自己训练一下就好了
