### ISSUE TITLE
能否支持多种类别文本的标化

### ISSUE THREAD

**Issue by andylulu** [GanjinZero/CHIP2020_term_normalization#7]
比如有疾病诊断、手术、收费项目、检查检验单等多种类别输入文本，用这套模型可以吗？还是说要分单个类别来处理？

**Comment by GanjinZero** [comment]
这个模型是设计用来进行疾病名称标准化的，如果你的训练数据输入格式和该数据集本身类似就可以使用。如果你没有训练数据，那这个模型只能用来在疾病上使用。
